# Generated by Django 4.2.7 on 2025-08-07 20:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='Stock ticker symbol (e.g., AAPL, GOOGL)', max_length=10, unique=True)),
                ('name', models.CharField(help_text='Company name (e.g., Apple Inc.)', max_length=100)),
                ('current_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Current stock price in USD', max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text="Whether we're actively tracking this stock")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['symbol'],
            },
        ),
    ]
